[2021-07-17 10:34:39,099] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl 2021-07-17T10:34:36.312050+00:00 [queued]>
[2021-07-17 10:34:39,133] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spotify_dag.spotify_etl 2021-07-17T10:34:36.312050+00:00 [queued]>
[2021-07-17 10:34:39,136] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 10:34:39,137] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-07-17 10:34:39,138] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 10:34:39,160] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): spotify_etl> on 2021-07-17T10:34:36.312050+00:00
[2021-07-17 10:34:39,167] {standard_task_runner.py:52} INFO - Started process 5051 to run task
[2021-07-17 10:34:39,176] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'spotify_etl', '2021-07-17T10:34:36.312050+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmp2bat0k31', '--error-file', '/tmp/tmpbgciskvb']
[2021-07-17 10:34:39,178] {standard_task_runner.py:77} INFO - Job 178: Subtask spotify_etl
[2021-07-17 10:34:39,252] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify_dag.spotify_etl 2021-07-17T10:34:36.312050+00:00 [running]> on host 47b2820c0b7e
[2021-07-17 10:34:39,340] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_dag
AIRFLOW_CTX_TASK_ID=spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-07-17T10:34:36.312050+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-17T10:34:36.312050+00:00
[2021-07-17 10:34:40,326] {logging_mixin.py:104} INFO -                                   unique_identifier  ...               artist_id
0   4dljlmVE5RTpAiEwCi6kkD-2021-07-17T06:38:09.115Z  ...  0LyfQWJT6nXafLPZqxe9Of
1   2BgEsaKNfHUdlh97KmvFyo-2021-07-17T06:20:00.932Z  ...  1zNqDE7qDGCsyzJwohVaoX
2   6FB3v4YcR57y4tXFcdxI1E-2021-07-17T05:57:29.563Z  ...  06HL4z0CvFAxyc27GXpf02
3   079Ey5uxL04AKPQgVQwx5h-2021-07-17T05:52:09.733Z  ...  0C8ZW7ezQVs4URX5aX7Kqx
4   4l0Mvzj72xxOpRrp6h8nHi-2021-07-17T05:34:32.537Z  ...  0C8ZW7ezQVs4URX5aX7Kqx
5   68iBMrMRc1rg4eAxJbvxch-2021-07-17T02:47:19.534Z  ...  1OPqAyxsQc8mcRmoNBAnVk
6   1YMLgvsQdE27r30q0fsLeV-2021-07-17T02:44:04.538Z  ...  0sSxphmGskGCKlwB9xa6WU
7   4TAdD9qxGEZR8hQQL3DXH8-2021-07-17T02:38:23.271Z  ...  4IKVDbCSBTxBeAsMKjAuTs
8   5qtEWwRUX3GKgpWwDQf9SA-2021-07-17T02:33:13.613Z  ...  1wRPtKGflJrBx9BmLsSwlU
9   7rMqbvNImA6wy8lxlNUMmj-2021-07-17T02:28:55.079Z  ...  09UmIX92EUH9hAK4bxvHx6
10  2Fv2injs4qAm8mJBGaxVKU-2021-07-17T02:23:43.585Z  ...  4YRxDV8wJFPHPTeXepOstw
11  0qPLlSlMNQgI3z6wykpL8R-2021-07-17T02:18:58.304Z  ...  0LyfQWJT6nXafLPZqxe9Of
12  4dljlmVE5RTpAiEwCi6kkD-2021-07-17T02:14:57.757Z  ...  0LyfQWJT6nXafLPZqxe9Of
13  4dljlmVE5RTpAiEwCi6kkD-2021-07-17T01:55:08.725Z  ...  0LyfQWJT6nXafLPZqxe9Of

[14 rows x 9 columns]
[2021-07-17 10:34:40,385] {logging_mixin.py:104} INFO -                   album_id  ...                                                url
0   5Mpodk3gBVn1eSAVlfbci4  ...  https://open.spotify.com/album/5Mpodk3gBVn1eSA...
1   7lPoGKpCGgdKFAxpudhAH5  ...  https://open.spotify.com/album/7lPoGKpCGgdKFAx...
2   4jTYApZPMapg56gRycOn0D  ...  https://open.spotify.com/album/4jTYApZPMapg56g...
3   2jGa3OwXatFYQAIS7OV7k9  ...  https://open.spotify.com/album/2jGa3OwXatFYQAI...
4   3YPFaTR7WMi1Hd4NVKdCJx  ...  https://open.spotify.com/album/3YPFaTR7WMi1Hd4...
5   3Qx3ApbCoc45FxqRVkty7E  ...  https://open.spotify.com/album/3Qx3ApbCoc45Fxq...
6   3RtFFza4brQXoNSv19g1ps  ...  https://open.spotify.com/album/3RtFFza4brQXoNS...
7   2Z5Dq0EmYGI7yUTIgRnuSY  ...  https://open.spotify.com/album/2Z5Dq0EmYGI7yUT...
8   2Svje8vKEM4VCKxoRyAvA4  ...  https://open.spotify.com/album/2Svje8vKEM4VCKx...
9   0gCcyIYaX8OK2BcKs8behf  ...  https://open.spotify.com/album/0gCcyIYaX8OK2Bc...
10  3I8PdIhk6pNm8Kv0HiF14V  ...  https://open.spotify.com/album/3I8PdIhk6pNm8Kv...
11  1JwvJZhFfcC2vFIuYTZlxF  ...  https://open.spotify.com/album/1JwvJZhFfcC2vFI...

[12 rows x 5 columns]
[2021-07-17 10:34:40,449] {logging_mixin.py:104} INFO -                  artist_id  ...                                                url
0   4YRxDV8wJFPHPTeXepOstw  ...  https://open.spotify.com/artist/4YRxDV8wJFPHPT...
1   1zNqDE7qDGCsyzJwohVaoX  ...  https://open.spotify.com/artist/1zNqDE7qDGCsyz...
2   06HL4z0CvFAxyc27GXpf02  ...  https://open.spotify.com/artist/06HL4z0CvFAxyc...
3   0C8ZW7ezQVs4URX5aX7Kqx  ...  https://open.spotify.com/artist/0C8ZW7ezQVs4UR...
4   1mcTU81TzQhprhouKaTkpq  ...  https://open.spotify.com/artist/1mcTU81TzQhprh...
6   1OPqAyxsQc8mcRmoNBAnVk  ...  https://open.spotify.com/artist/1OPqAyxsQc8mcR...
7   4f7KfxeHq9BiylGmyXepGt  ...  https://open.spotify.com/artist/4f7KfxeHq9Biyl...
8   6AwwLwgIsTIXZ8kHWaZUj5  ...  https://open.spotify.com/artist/6AwwLwgIsTIXZ8...
10  76fuWYgIf3TVIopTs3vaJ6  ...  https://open.spotify.com/artist/76fuWYgIf3TVIo...
11  4IKVDbCSBTxBeAsMKjAuTs  ...  https://open.spotify.com/artist/4IKVDbCSBTxBeA...
12  3yMmYEklQ7gLOZXEFNd3xr  ...  https://open.spotify.com/artist/3yMmYEklQ7gLOZ...
13  1wRPtKGflJrBx9BmLsSwlU  ...  https://open.spotify.com/artist/1wRPtKGflJrBx9...
15  09UmIX92EUH9hAK4bxvHx6  ...  https://open.spotify.com/artist/09UmIX92EUH9hA...
16  5GnnSrwNCGyfAU4zuIytiS  ...  https://open.spotify.com/artist/5GnnSrwNCGyfAU...
17  19MVxKZZdPj2X0F8pi0OCT  ...  https://open.spotify.com/artist/19MVxKZZdPj2X0...
18  0y59o4v8uw5crbN9M3JiL1  ...  https://open.spotify.com/artist/0y59o4v8uw5crb...
19  2KhDedackjZfysiu7T7AwN  ...  https://open.spotify.com/artist/2KhDedackjZfys...
20  1ZCPRtzF2CRFnP9OYHQGmN  ...  https://open.spotify.com/artist/1ZCPRtzF2CRFnP...
21  7qATomOqJzoJiuEpAaxOXd  ...  https://open.spotify.com/artist/7qATomOqJzoJiu...
24  6UXtWzEh7DSBepGmaq7tXk  ...  https://open.spotify.com/artist/6UXtWzEh7DSBep...
25  4VS3XraXs2LRsowQnQ7VFh  ...  https://open.spotify.com/artist/4VS3XraXs2LRso...
26  4OFVqZNj0INA51VvzK3Lgw  ...  https://open.spotify.com/artist/4OFVqZNj0INA51...
27  0oOet2f43PA68X5RxKobEy  ...  https://open.spotify.com/artist/0oOet2f43PA68X...
28  0vkpFzbSTmwPuGGnhsblFI  ...  https://open.spotify.com/artist/0vkpFzbSTmwPuG...
29  418X5slNWlJwym4x3Oq3Cs  ...  https://open.spotify.com/artist/418X5slNWlJwym...
30  0KDEADL3DeTLtENG3DliCd  ...  https://open.spotify.com/artist/0KDEADL3DeTLtE...
31  6jf2eKjiPT6P18RbOSLzf0  ...  https://open.spotify.com/artist/6jf2eKjiPT6P18...
32  5u8D5g7TS3cNK5C4NU9mhV  ...  https://open.spotify.com/artist/5u8D5g7TS3cNK5...
34  2wEKXEd9OLGLX8Q5CRwcJS  ...  https://open.spotify.com/artist/2wEKXEd9OLGLX8...
35  4FJhE5ToBQGzOGf0D5Xd1C  ...  https://open.spotify.com/artist/4FJhE5ToBQGzOG...
36  5wQDQFm7Ku8WWGi5xqJ9lp  ...  https://open.spotify.com/artist/5wQDQFm7Ku8WWG...
37  3eDT9fwXKuHWFvgZaaYC5v  ...  https://open.spotify.com/artist/3eDT9fwXKuHWFv...
38  3xU8YsNNkmWSPewlB18NUz  ...  https://open.spotify.com/artist/3xU8YsNNkmWSPe...
39  2FV0sdO6uDLDe73NGLUQQq  ...  https://open.spotify.com/artist/2FV0sdO6uDLDe7...
40  5fvTHKKzW44A9867nPDocM  ...  https://open.spotify.com/artist/5fvTHKKzW44A98...
41  7HCqGPJcQTyGJ2yqntbuyr  ...  https://open.spotify.com/artist/7HCqGPJcQTyGJ2...
42  5LZ894xYE9MG1sal0gjt5L  ...  https://open.spotify.com/artist/5LZ894xYE9MG1s...
43  6RqKw1rO5NTdnowovO35qF  ...  https://open.spotify.com/artist/6RqKw1rO5NTdno...
44  3dN9MQpjIyNxyeRfz4EDZe  ...  https://open.spotify.com/artist/3dN9MQpjIyNxye...
45  6zsgSg6Sei0eS5L4Sk4tdo  ...  https://open.spotify.com/artist/6zsgSg6Sei0eS5...
46  2bIg95CGHmriFZX7MsnFRK  ...  https://open.spotify.com/artist/2bIg95CGHmriFZ...
47  04FsFHujpuqonrPXZrEJlK  ...  https://open.spotify.com/artist/04FsFHujpuqonr...
49  2oSONSC9zQ4UonDKnLqksx  ...  https://open.spotify.com/artist/2oSONSC9zQ4Uon...

[43 rows x 3 columns]
[2021-07-17 10:34:40,475] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_etl.py", line 95, in spotify_etl_run
    song_df.to_sql("songs", engine, index=False,if_exists='replace')
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 2615, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 598, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1393, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 721, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 708, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1431, in has_table
    self.connectable.dialect.has_table, name, schema or self.meta.schema
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2211, in run_callable
    with self._contextual_connect() as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-07-17 10:34:40,508] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=spotify_etl, execution_date=20210717T103436, start_date=20210717T103439, end_date=20210717T103440
[2021-07-17 10:34:40,598] {local_task_job.py:149} INFO - Task exited with return code 1
